name: walleto_dart_api
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
   args: ^2.3.1
   shelf: ^1.1.0
   shelf_router: ^1.1.3
   dotenv: ^3.0.0
   mysql1: ^0.20.0
   get_it: ^7.2.0
   logger: ^1.0.0
   injectable: ^2.1.0
   jaguar_jwt: ^3.0.0
   intl:
   ansicolor: ^2.0.1
   # socket_io:
   # socket_io_client:
   aws_client: ^0.6.0
  #  search_cep: ^4.0.2
   dio: ^5.4.3+1



dev_dependencies:
  shelf_router_generator: ^1.0.5
  logging: ^1.1.0
  pedantic: ^1.10.0
  injectable_generator: ^2.1.3
  build_runner: ^2.3.3
  crypto: ^3.0.0
  source_gen: ^1.2.6
  mailer: ^6.0.0
  analyzer: ^6.3.0
  
assets:
  - .env